import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const userId = user.id;
    const userEmail = user.email;
    const userName = user.full_name || 'Demo User';

    // 1. Create UserProfile
    const profile = await base44.entities.UserProfile.create({
      user_id: userId,
      account_type: 'both',
      national_id: 'CM8765432109WR',
      phone_number: '+256772345678',
      date_of_birth: '1992-03-15',
      gender: 'male',
      address: 'Plot 23, Nakasero Hill Road',
      district: 'Kampala',
      employment_status: 'self_employed',
      employer_name: 'Kampala Tech Services',
      job_title: 'Business Owner',
      monthly_income: 4500000,
      income_source: 'business',
      mobile_money_provider: 'mtn',
      mobile_money_account: '+256772345678',
      bank_name: 'Stanbic Bank',
      bank_account_number: '9034567890',
      bank_branch: 'Kampala Road',
      account_status: 'active',
      kyc_status: 'verified',
      aml_status: 'cleared',
      identity_verified: true,
      device_verified: true,
      duplicate_check_passed: true,
      verified_at: '2024-06-01T09:00:00Z',
      risk_tier: 'platinum',
      trust_score: 875,
      reputation_level: 'elite',
      borrower_badge: 'platinum_borrower',
      lender_reliability_score: 940,
      consecutive_on_time_payments: 28,
      total_loans_completed: 9,
      referral_code: `PIPIYA-${userName.split(' ')[0].toUpperCase()}-2024`,
      referral_count: 15,
      successful_referrals_count: 11,
      loyalty_points: 5850,
      profile_completion_pct: 100,
      preferred_risk_bands: ['A', 'B'],
      lender_notify_in_app: true,
      lender_min_investment: 100000,
      lender_max_investment: 3000000,
      lender_notify_purpose_categories: ['business', 'agriculture', 'education'],
      description: 'Elite customer with excellent credit history and active P2P lender',
    });

    // 2. Create Credit Score history (2 years)
    const creditScores = await base44.entities.CreditScore.bulkCreate([
      {
        user_id: userId,
        score: 520,
        risk_band: 'D',
        calculated_at: '2024-06-01T10:00:00Z',
        description: 'Initial credit score - new customer',
        score_breakdown: {
          kyc_score: 60,
          repayment_score: 50,
          loan_history_score: 45,
          savings_boost: 30,
          expense_boost: 25,
          income_score: 55,
        },
        reason_codes: ['limited_credit_history', 'new_customer'],
        max_loan_limit: 1500000,
      },
      {
        user_id: userId,
        score: 595,
        risk_band: 'C',
        calculated_at: '2024-09-15T10:00:00Z',
        description: 'Score improved after first loan repayment',
        score_breakdown: {
          kyc_score: 75,
          repayment_score: 65,
          loan_history_score: 60,
          savings_boost: 40,
          expense_boost: 35,
          income_score: 60,
        },
        reason_codes: ['on_time_payments', 'completed_first_loan'],
        max_loan_limit: 2500000,
      },
      {
        user_id: userId,
        score: 665,
        risk_band: 'B',
        calculated_at: '2025-01-10T10:00:00Z',
        description: 'Consistent repayments and savings growth',
        score_breakdown: {
          kyc_score: 85,
          repayment_score: 75,
          loan_history_score: 70,
          savings_boost: 55,
          expense_boost: 50,
          income_score: 65,
        },
        reason_codes: ['consistent_repayments', 'growing_savings', 'income_verified'],
        max_loan_limit: 5000000,
      },
      {
        user_id: userId,
        score: 725,
        risk_band: 'B',
        calculated_at: '2025-06-20T10:00:00Z',
        description: 'Multiple successful loans completed',
        score_breakdown: {
          kyc_score: 90,
          repayment_score: 85,
          loan_history_score: 80,
          savings_boost: 65,
          expense_boost: 60,
          income_score: 70,
        },
        reason_codes: ['multiple_loans_completed', 'excellent_payment_history'],
        max_loan_limit: 8000000,
      },
      {
        user_id: userId,
        score: 780,
        risk_band: 'A',
        calculated_at: '2025-12-01T10:00:00Z',
        description: 'Platinum tier achieved - elite customer',
        score_breakdown: {
          kyc_score: 95,
          repayment_score: 92,
          loan_history_score: 88,
          savings_boost: 75,
          expense_boost: 70,
          income_score: 78,
        },
        reason_codes: ['platinum_tier', 'elite_status', 'consistent_income'],
        max_loan_limit: 12000000,
      },
      {
        user_id: userId,
        score: 815,
        risk_band: 'A',
        calculated_at: '2026-05-20T10:00:00Z',
        description: 'Current score - excellent creditworthiness',
        score_breakdown: {
          kyc_score: 98,
          repayment_score: 95,
          loan_history_score: 92,
          savings_boost: 82,
          expense_boost: 78,
          income_score: 82,
        },
        reason_codes: ['excellent_credit', 'platinum_borrower', 'active_lender'],
        max_loan_limit: 15000000,
      },
    ]);

    // 3. Create Loan Applications (2 years history - 9 loans total)
    const loans = await base44.entities.LoanApplication.bulkCreate([
      // Loan 1: 2024-06 - Small business equipment (CLOSED)
      {
        user_id: userId,
        amount_requested: 2000000,
        amount_approved: 2000000,
        purpose: 'Business Equipment',
        tenure_months: 6,
        interest_rate: 10.5,
        risk_band: 'C',
        risk_band_at_application: 'C',
        credit_score_at_application: 520,
        status: 'closed',
        monthly_installment: 350000,
        total_repayable: 2100000,
        disbursed_at: '2024-06-15T10:00:00Z',
        next_repayment_date: '2024-07-15',
        outstanding_balance: 0,
        disbursement_fee: 60000,
        insurance_cost: 20000,
        net_disbursement: 1920000,
        description: 'First loan - laptop and printer for freelance work',
      },
      // Loan 2: 2024-09 - Home improvement (CLOSED)
      {
        user_id: userId,
        amount_requested: 3500000,
        amount_approved: 3500000,
        purpose: 'Home Improvement',
        tenure_months: 9,
        interest_rate: 9.5,
        risk_band: 'C',
        risk_band_at_application: 'C',
        credit_score_at_application: 595,
        status: 'closed',
        monthly_installment: 420000,
        total_repayable: 3780000,
        disbursed_at: '2024-09-20T10:00:00Z',
        next_repayment_date: '2024-10-20',
        outstanding_balance: 0,
        disbursement_fee: 105000,
        insurance_cost: 35000,
        net_disbursement: 3360000,
        description: 'Second loan - home renovation and solar installation',
      },
      // Loan 3: 2025-01 - Vehicle purchase (CLOSED)
      {
        user_id: userId,
        amount_requested: 5000000,
        amount_approved: 5000000,
        purpose: 'Vehicle Purchase',
        tenure_months: 12,
        interest_rate: 8.5,
        risk_band: 'B',
        risk_band_at_application: 'B',
        credit_score_at_application: 665,
        status: 'closed',
        monthly_installment: 450000,
        total_repayable: 5400000,
        disbursed_at: '2025-01-10T10:00:00Z',
        next_repayment_date: '2025-02-10',
        outstanding_balance: 0,
        disbursement_fee: 150000,
        insurance_cost: 50000,
        net_disbursement: 4800000,
        description: 'Third loan - motorcycle for transport business',
      },
      // Loan 4: 2025-04 - Inventory financing (CLOSED)
      {
        user_id: userId,
        amount_requested: 4000000,
        amount_approved: 4000000,
        purpose: 'Business Inventory',
        tenure_months: 8,
        interest_rate: 8.0,
        risk_band: 'B',
        risk_band_at_application: 'B',
        credit_score_at_application: 695,
        status: 'closed',
        monthly_installment: 530000,
        total_repayable: 4240000,
        disbursed_at: '2025-04-05T10:00:00Z',
        outstanding_balance: 0,
        disbursement_fee: 120000,
        insurance_cost: 40000,
        net_disbursement: 3840000,
        description: 'Inventory stock for electronics retail business',
      },
      // Loan 5: 2025-07 - Agricultural equipment (CLOSED)
      {
        user_id: userId,
        amount_requested: 6000000,
        amount_approved: 6000000,
        purpose: 'Agriculture',
        tenure_months: 12,
        interest_rate: 7.5,
        risk_band: 'B',
        risk_band_at_application: 'B',
        credit_score_at_application: 710,
        status: 'closed',
        monthly_installment: 530000,
        total_repayable: 6360000,
        disbursed_at: '2025-07-15T10:00:00Z',
        outstanding_balance: 0,
        disbursement_fee: 180000,
        insurance_cost: 60000,
        net_disbursement: 5760000,
        description: 'Irrigation system and farming equipment for rural farm',
      },
      // Loan 6: 2025-10 - Education fees (CLOSED)
      {
        user_id: userId,
        amount_requested: 3000000,
        amount_approved: 3000000,
        purpose: 'Education',
        tenure_months: 6,
        interest_rate: 7.0,
        risk_band: 'A',
        risk_band_at_application: 'A',
        credit_score_at_application: 725,
        status: 'closed',
        monthly_installment: 515000,
        total_repayable: 3090000,
        disbursed_at: '2025-10-01T10:00:00Z',
        outstanding_balance: 0,
        disbursement_fee: 90000,
        insurance_cost: 30000,
        net_disbursement: 2880000,
        description: 'Professional certification and MBA tuition fees',
      },
      // Loan 7: 2025-12 - Business expansion (ACTIVE)
      {
        user_id: userId,
        amount_requested: 8000000,
        amount_approved: 8000000,
        purpose: 'Business Expansion',
        tenure_months: 18,
        interest_rate: 7.5,
        risk_band: 'A',
        risk_band_at_application: 'A',
        credit_score_at_application: 750,
        status: 'active',
        monthly_installment: 480000,
        total_repayable: 8640000,
        disbursed_at: '2025-12-01T10:00:00Z',
        next_repayment_date: '2026-06-01',
        outstanding_balance: 3200000,
        disbursement_fee: 240000,
        insurance_cost: 80000,
        net_disbursement: 7680000,
        description: 'Expand transport business - additional motorcycles',
      },
      // Loan 8: 2026-02 - Real estate investment (ACTIVE)
      {
        user_id: userId,
        amount_requested: 10000000,
        amount_approved: 10000000,
        purpose: 'Real Estate',
        tenure_months: 24,
        interest_rate: 7.0,
        risk_band: 'A',
        risk_band_at_application: 'A',
        credit_score_at_application: 780,
        status: 'active',
        monthly_installment: 450000,
        total_repayable: 10800000,
        disbursed_at: '2026-02-01T10:00:00Z',
        next_repayment_date: '2026-06-01',
        outstanding_balance: 8100000,
        disbursement_fee: 300000,
        insurance_cost: 100000,
        net_disbursement: 9600000,
        description: 'Land purchase for future commercial development',
      },
      // Loan 9: 2026-05 - Working capital (ACTIVE - just disbursed)
      {
        user_id: userId,
        amount_requested: 5000000,
        amount_approved: 5000000,
        purpose: 'Working Capital',
        tenure_months: 12,
        interest_rate: 6.5,
        risk_band: 'A',
        risk_band_at_application: 'A',
        credit_score_at_application: 815,
        status: 'disbursed',
        monthly_installment: 435000,
        total_repayable: 5220000,
        disbursed_at: '2026-05-20T10:00:00Z',
        next_repayment_date: '2026-06-20',
        outstanding_balance: 5000000,
        disbursement_fee: 150000,
        insurance_cost: 50000,
        net_disbursement: 4800000,
        description: 'Working capital for Q3 business operations',
      },
    ]);

    // 4. Create Repayment records (historical payments for closed loans + active loan payments)
    const repayments = await base44.entities.Repayment.bulkCreate([
      // Loan 1 repayments (6 months - completed)
      ...Array.from({ length: 6 }, (_, i) => ({
        loan_id: loans[0].id,
        user_id: userId,
        amount: 350000,
        due_date: new Date(2024, 6 + i, 15).toISOString().split('T')[0],
        paid_date: new Date(2024, 6 + i, 13 + (i % 3)).toISOString().split('T')[0],
        status: 'paid',
        payment_method: i % 2 === 0 ? 'mobile_money' : 'bank_transfer',
        transaction_ref: `TXN-2024-L1-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/6 - Business Equipment Loan`,
      })),
      // Loan 2 repayments (9 months - completed)
      ...Array.from({ length: 9 }, (_, i) => ({
        loan_id: loans[1].id,
        user_id: userId,
        amount: 420000,
        due_date: new Date(2024, 9 + i, 20).toISOString().split('T')[0],
        paid_date: new Date(2024, 9 + i, 18 + (i % 3)).toISOString().split('T')[0],
        status: 'paid',
        payment_method: i % 3 === 0 ? 'mobile_money' : 'bank_transfer',
        transaction_ref: `TXN-2024-L2-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/9 - Home Improvement Loan`,
      })),
      // Loan 3 repayments (12 months - completed)
      ...Array.from({ length: 12 }, (_, i) => ({
        loan_id: loans[2].id,
        user_id: userId,
        amount: 450000,
        due_date: new Date(2025, i, 10).toISOString().split('T')[0],
        paid_date: new Date(2025, i, 8 + (i % 3)).toISOString().split('T')[0],
        status: 'paid',
        payment_method: i % 2 === 0 ? 'mobile_money' : 'wallet',
        transaction_ref: `TXN-2025-L3-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/12 - Vehicle Purchase Loan`,
      })),
      // Loan 4 repayments (8 months - completed)
      ...Array.from({ length: 8 }, (_, i) => ({
        loan_id: loans[3].id,
        user_id: userId,
        amount: 530000,
        due_date: new Date(2025, 3 + i, 5).toISOString().split('T')[0],
        paid_date: new Date(2025, 3 + i, 3 + (i % 2)).toISOString().split('T')[0],
        status: 'paid',
        payment_method: 'mobile_money',
        transaction_ref: `TXN-2025-L4-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/8 - Inventory Financing`,
      })),
      // Loan 5 repayments (12 months - completed)
      ...Array.from({ length: 12 }, (_, i) => ({
        loan_id: loans[4].id,
        user_id: userId,
        amount: 530000,
        due_date: new Date(2025, 6 + i, 15).toISOString().split('T')[0],
        paid_date: new Date(2025, 6 + i, 13 + (i % 2)).toISOString().split('T')[0],
        status: 'paid',
        payment_method: i % 3 === 0 ? 'bank_transfer' : 'mobile_money',
        transaction_ref: `TXN-2025-L5-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/12 - Agricultural Equipment`,
      })),
      // Loan 6 repayments (6 months - completed)
      ...Array.from({ length: 6 }, (_, i) => ({
        loan_id: loans[5].id,
        user_id: userId,
        amount: 515000,
        due_date: new Date(2025, 9 + i, 1).toISOString().split('T')[0],
        paid_date: new Date(2025, 9 + i, 1).toISOString().split('T')[0],
        status: 'paid',
        payment_method: 'bank_transfer',
        transaction_ref: `TXN-2025-L6-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/6 - Education Fees`,
      })),
      // Loan 7 repayments (6 of 18 months paid)
      ...Array.from({ length: 6 }, (_, i) => ({
        loan_id: loans[6].id,
        user_id: userId,
        amount: 480000,
        due_date: new Date(2025, 11 + i, 1).toISOString().split('T')[0],
        paid_date: new Date(2025, 11 + i, 1).toISOString().split('T')[0],
        status: 'paid',
        payment_method: 'mobile_money',
        transaction_ref: `TXN-2026-L7-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/18 - Business Expansion`,
      })),
      // Add upcoming repayment for Loan 7
      {
        loan_id: loans[6].id,
        user_id: userId,
        amount: 480000,
        due_date: '2026-06-01',
        status: 'scheduled',
        description: 'Installment 7/18 - Business Expansion',
      },
      // Loan 8 repayments (3 of 24 months paid)
      ...Array.from({ length: 3 }, (_, i) => ({
        loan_id: loans[7].id,
        user_id: userId,
        amount: 450000,
        due_date: new Date(2026, 1 + i, 1).toISOString().split('T')[0],
        paid_date: new Date(2026, 1 + i, 1).toISOString().split('T')[0],
        status: 'paid',
        payment_method: 'bank_transfer',
        transaction_ref: `TXN-2026-L8-${String(i + 1).padStart(3, '0')}`,
        description: `Installment ${i + 1}/24 - Real Estate Investment`,
      })),
      // Add upcoming repayment for Loan 8
      {
        loan_id: loans[7].id,
        user_id: userId,
        amount: 450000,
        due_date: '2026-06-01',
        status: 'scheduled',
        description: 'Installment 4/24 - Real Estate Investment',
      },
      // Loan 9 - first repayment upcoming
      {
        loan_id: loans[8].id,
        user_id: userId,
        amount: 435000,
        due_date: '2026-06-20',
        status: 'scheduled',
        description: 'Installment 1/12 - Working Capital',
      },
    ]);

    // 5. Create Savings Pockets
    const pockets = await base44.entities.SavingsPocket.bulkCreate([
      {
        user_id: userId,
        name: 'House Down Payment',
        goal_amount: 50000000,
        current_balance: 32500000,
        icon: '🏠',
        color: '#006B3C',
        auto_save_frequency: 'monthly',
        auto_save_amount: 500000,
        status: 'active',
        target_date: '2028-05-24',
        description: 'Saving for residential property in Nakasero',
      },
      {
        user_id: userId,
        name: 'Business Emergency Fund',
        goal_amount: 20000000,
        current_balance: 18200000,
        icon: '💼',
        color: '#F4B400',
        auto_save_frequency: 'weekly',
        auto_save_amount: 100000,
        status: 'active',
        target_date: '2026-12-31',
        description: '6 months operating expenses reserve',
      },
      {
        user_id: userId,
        name: 'Children Education',
        goal_amount: 30000000,
        current_balance: 15800000,
        icon: '📚',
        color: '#7BC943',
        auto_save_frequency: 'monthly',
        auto_save_amount: 300000,
        status: 'active',
        target_date: '2029-01-01',
        description: 'University education fund for 3 children',
      },
      {
        user_id: userId,
        name: 'Car Replacement Fund',
        goal_amount: 25000000,
        current_balance: 12400000,
        icon: '🚗',
        color: '#007a44',
        auto_save_frequency: 'monthly',
        auto_save_amount: 400000,
        status: 'active',
        target_date: '2027-06-30',
        description: 'Replace current motorcycle with car',
      },
      {
        user_id: userId,
        name: 'Medical Emergency',
        goal_amount: 10000000,
        current_balance: 8900000,
        icon: '💊',
        color: '#dc2626',
        auto_save_frequency: 'weekly',
        auto_save_amount: 50000,
        status: 'active',
        target_date: '2026-12-31',
        description: 'Family health emergency fund',
      },
    ]);

    // 6. Create Insurance Policies
    const policies = await base44.entities.InsurancePolicy.bulkCreate([
      {
        user_id: userId,
        product_id: 'vehicle_comprehensive',
        policy_number: 'POL-VEH-2024-0892',
        status: 'active',
        coverage_amount: 25000000,
        premium_amount: 450000,
        premium_frequency: 'quarterly',
        start_date: '2024-06-01',
        end_date: '2027-06-01',
        next_premium_date: '2026-09-01',
        asset_description: '2022 TVS Raider 125cc - Registration UBD 567K',
        asset_value: 25000000,
        total_premiums_paid: 8100000,
        beneficiary_name: 'Sarah Nakato',
        beneficiary_relationship: 'spouse',
        beneficiary_phone: '+256772345679',
      },
      {
        user_id: userId,
        product_id: 'health_family',
        policy_number: 'POL-HLTH-2024-1234',
        status: 'active',
        coverage_amount: 50000000,
        premium_amount: 380000,
        premium_frequency: 'monthly',
        start_date: '2024-07-01',
        end_date: '2027-07-01',
        next_premium_date: '2026-06-01',
        asset_description: 'Family plan - spouse + 3 children',
        total_premiums_paid: 8740000,
        beneficiary_name: 'Self',
      },
      {
        user_id: userId,
        product_id: 'loan_protection',
        policy_number: 'POL-LP-2025-0456',
        status: 'active',
        coverage_amount: 8000000,
        premium_amount: 80000,
        premium_frequency: 'annual',
        start_date: '2025-12-01',
        end_date: '2027-12-01',
        next_premium_date: '2026-12-01',
        asset_description: 'Loan protection for Business Expansion loan',
        total_premiums_paid: 80000,
      },
      {
        user_id: userId,
        product_id: 'loan_protection',
        policy_number: 'POL-LP-2026-0789',
        status: 'active',
        coverage_amount: 10000000,
        premium_amount: 100000,
        premium_frequency: 'annual',
        start_date: '2026-02-01',
        end_date: '2028-02-01',
        next_premium_date: '2027-02-01',
        asset_description: 'Loan protection for Real Estate loan',
        total_premiums_paid: 100000,
      },
      {
        user_id: userId,
        product_id: 'property_fire',
        policy_number: 'POL-PROP-2025-0321',
        status: 'active',
        coverage_amount: 80000000,
        premium_amount: 1200000,
        premium_frequency: 'annual',
        start_date: '2025-08-15',
        end_date: '2027-08-15',
        next_premium_date: '2026-08-15',
        asset_description: 'Commercial property - Kampala Road business premises',
        asset_value: 80000000,
        total_premiums_paid: 1200000,
      },
      {
        user_id: userId,
        product_id: 'life_term',
        policy_number: 'POL-LIFE-2024-0567',
        status: 'active',
        coverage_amount: 100000000,
        premium_amount: 850000,
        premium_frequency: 'quarterly',
        start_date: '2024-09-01',
        end_date: '2034-09-01',
        next_premium_date: '2026-09-01',
        asset_description: '20-year term life insurance',
        total_premiums_paid: 15300000,
        beneficiary_name: 'Sarah Nakato',
        beneficiary_relationship: 'spouse',
        beneficiary_phone: '+256772345679',
      },
    ]);

    // 7. Create Lender Investments (P2P)
    const investments = await base44.entities.LenderInvestment.bulkCreate([
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_001',
        investment_type: 'manual',
        amount_invested: 2500000,
        ownership_pct: 12.5,
        expected_return: 375000,
        actual_return_earned: 198000,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2025-03-15T10:00:00Z',
        maturity_date: '2027-03-15',
        description: 'Investment in agricultural equipment loan - Farmer John',
      },
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_002',
        investment_type: 'auto_pool',
        amount_invested: 1500000,
        ownership_pct: 8.3,
        expected_return: 225000,
        actual_return_earned: 142000,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2025-05-20T10:00:00Z',
        maturity_date: '2026-11-20',
        description: 'Auto-pool investment - diversified portfolio',
      },
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_003',
        investment_type: 'manual',
        amount_invested: 3000000,
        ownership_pct: 15.0,
        expected_return: 480000,
        actual_return_earned: 256000,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2025-08-10T10:00:00Z',
        maturity_date: '2027-08-10',
        description: 'Investment in small business - retail shop expansion',
      },
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_004',
        investment_type: 'manual',
        amount_invested: 2000000,
        ownership_pct: 10.0,
        expected_return: 320000,
        actual_return_earned: 89000,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2026-01-15T10:00:00Z',
        maturity_date: '2027-07-15',
        description: 'Investment in education loan - medical student',
      },
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_005',
        investment_type: 'auto_pool',
        amount_invested: 1000000,
        ownership_pct: 5.5,
        expected_return: 160000,
        actual_return_earned: 32000,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2026-04-01T10:00:00Z',
        maturity_date: '2027-04-01',
        description: 'Auto-pool investment - Q2 2026',
      },
      {
        lender_id: userId,
        lender_profile_id: profile.id,
        loan_id: 'p2p_loan_006',
        investment_type: 'manual',
        amount_invested: 5000000,
        ownership_pct: 20.0,
        expected_return: 800000,
        actual_return_earned: 0,
        status: 'active',
        lender_share_pct: 55,
        platform_share_pct: 30,
        reserve_share_pct: 15,
        invested_at: '2026-05-15T10:00:00Z',
        maturity_date: '2028-05-15',
        description: 'Investment in real estate development loan',
      },
    ]);

    // 8. Create Expenses (2 years - sample monthly expenses)
    const expenses = await base44.entities.Expense.bulkCreate([
      // 2024 expenses (sample - 3 per month average)
      ...Array.from({ length: 24 }, (_, i) => {
        const month = i % 12;
        const year = 2024 + Math.floor(i / 12);
        const categories = ['food', 'transport', 'housing', 'utilities', 'entertainment', 'health'];
        const amounts = [150000, 80000, 500000, 120000, 200000, 100000];
        return {
          user_id: userId,
          amount: amounts[month % 6] * (1 + Math.random() * 0.3),
          category: categories[month % 6],
          date: new Date(year, month, 15).toISOString().split('T')[0],
          description: `${categories[month % 6]} expense`,
        };
      }),
      // Additional specific expenses
      { user_id: userId, amount: 2500000, category: 'housing', date: '2024-06-15', description: 'Rent payment Q2' },
      { user_id: userId, amount: 1800000, category: 'education', date: '2024-08-20', description: 'School fees - Term 3' },
      { user_id: userId, amount: 3200000, category: 'housing', date: '2025-01-10', description: 'Rent payment Q1 2025' },
      { user_id: userId, amount: 2100000, category: 'education', date: '2025-05-15', description: 'University tuition' },
      { user_id: userId, amount: 4500000, category: 'other', date: '2025-09-01', description: 'Family vacation - Murchison Falls' },
      { user_id: userId, amount: 2800000, category: 'housing', date: '2026-01-05', description: 'Rent payment Q1 2026' },
      { user_id: userId, amount: 2400000, category: 'education', date: '2026-02-10', description: 'School fees - Term 1' },
      { user_id: userId, amount: 1500000, category: 'health', date: '2026-04-20', description: 'Medical checkup and insurance' },
    ]);

    // 9. Create Notifications
    const notifications = await base44.entities.Notification.bulkCreate([
      {
        user_id: userId,
        title: 'Loan Approved!',
        body: 'Your loan application for UGX 5,000,000 has been approved. Disbursement will be processed within 24 hours.',
        type: 'loan_approved',
        is_read: true,
        priority: 'high',
        action_url: '/loans',
      },
      {
        user_id: userId,
        title: 'Repayment Due Tomorrow',
        body: 'Your loan installment of UGX 480,000 is due tomorrow. Ensure sufficient balance in your account.',
        type: 'repayment_due',
        is_read: false,
        priority: 'urgent',
        action_url: '/loans/repay',
      },
      {
        user_id: userId,
        title: 'Credit Score Increased!',
        body: 'Congratulations! Your credit score has increased to 815. You now qualify for platinum tier benefits.',
        type: 'gamification',
        is_read: true,
        priority: 'medium',
        action_url: '/credit-score',
      },
      {
        user_id: userId,
        title: 'Investment Return Received',
        body: 'You have received UGX 45,000 in returns from your P2P investment. Check your portfolio for details.',
        type: 'system',
        is_read: false,
        priority: 'low',
        action_url: '/invest',
      },
      {
        user_id: userId,
        title: 'Savings Goal Achieved!',
        body: 'Congratulations! You have reached your Business Emergency Fund goal of UGX 20,000,000.',
        type: 'savings_goal',
        is_read: true,
        priority: 'medium',
        action_url: '/savings',
      },
      {
        user_id: userId,
        title: 'KYC Verification Complete',
        body: 'Your identity verification has been successfully completed. Your account is now fully verified.',
        type: 'kyc_update',
        is_read: true,
        priority: 'high',
        action_url: '/profile',
      },
      {
        user_id: userId,
        title: 'Insurance Premium Due',
        body: 'Your vehicle insurance premium of UGX 450,000 is due on 2026-06-01. Pay now to avoid coverage lapse.',
        type: 'system',
        is_read: false,
        priority: 'high',
        action_url: '/insurance',
      },
      {
        user_id: userId,
        title: 'New Investment Opportunity',
        body: 'A new loan matching your preferences is available in the marketplace. Expected return: 14% annually.',
        type: 'nudge',
        is_read: false,
        priority: 'low',
        action_url: '/p2p/marketplace',
      },
      {
        user_id: userId,
        title: 'Loyalty Points Milestone',
        body: 'You have earned 5,000 loyalty points! Redeem them for fee discounts or cashback.',
        type: 'gamification',
        is_read: true,
        priority: 'medium',
        action_url: '/profile',
      },
      {
        user_id: userId,
        title: 'Repayment Reminder',
        body: 'This is a friendly reminder that your loan payment of UGX 435,000 is due on 2026-06-20.',
        type: 'repayment_due',
        is_read: false,
        priority: 'medium',
        action_url: '/loans/repay',
      },
    ]);

    // 10. Create Gamification Badges
    const badges = await base44.entities.GamificationBadge.bulkCreate([
      { user_id: userId, badge_type: 'first_loan_repaid', badge_name: 'First Steps', points_awarded: 100, earned_at: '2024-06-15T10:00:00Z', description: 'Completed your first loan application' },
      { user_id: userId, badge_type: 'on_time_streak_3', badge_name: 'Punctual Payer', points_awarded: 50, earned_at: '2024-07-15T10:00:00Z', description: 'Made first on-time payment' },
      { user_id: userId, badge_type: 'first_loan_repaid', badge_name: 'Loan Champion', points_awarded: 200, earned_at: '2024-12-15T10:00:00Z', description: 'Successfully completed first loan' },
      { user_id: userId, badge_type: 'first_savings', badge_name: 'Savings Starter', points_awarded: 75, earned_at: '2024-08-01T10:00:00Z', description: 'Reached UGX 1M in savings' },
      { user_id: userId, badge_type: 'kyc_complete', badge_name: 'Credit Builder', points_awarded: 100, earned_at: '2025-01-10T10:00:00Z', description: 'Achieved B risk band' },
      { user_id: userId, badge_type: 'referral_5', badge_name: 'Ambassador', points_awarded: 250, earned_at: '2025-03-20T10:00:00Z', description: 'Referred 5 successful users' },
      { user_id: userId, badge_type: 'first_loan_repaid', badge_name: 'First Investment', points_awarded: 150, earned_at: '2025-03-15T10:00:00Z', description: 'Made first P2P investment' },
      { user_id: userId, badge_type: 'kyc_complete', badge_name: 'Protected', points_awarded: 50, earned_at: '2024-06-01T10:00:00Z', description: 'Purchased first insurance policy' },
      { user_id: userId, badge_type: 'platinum_level', badge_name: 'Platinum Elite', points_awarded: 500, earned_at: '2025-12-01T10:00:00Z', description: 'Achieved platinum tier status' },
      { user_id: userId, badge_type: 'on_time_streak_12', badge_name: 'Reliable', points_awarded: 300, earned_at: '2026-01-01T10:00:00Z', description: '20 consecutive on-time payments' },
      { user_id: userId, badge_type: 'savings_goal_reached', badge_name: 'Goal Crusher', points_awarded: 200, earned_at: '2026-03-15T10:00:00Z', description: 'Completed first savings goal' },
      { user_id: userId, badge_type: 'budget_master', badge_name: 'Portfolio Master', points_awarded: 150, earned_at: '2026-05-01T10:00:00Z', description: 'Invested in 5 different loans' },
    ]);

    // 11. Create Loyalty Rewards
    const rewards = await base44.entities.LoyaltyReward.bulkCreate([
      {
        user_id: userId,
        profile_id: profile.id,
        reward_type: 'rate_reduction',
        reward_reason: 'on_time_payment',
        reward_value: 0.5,
        status: 'redeemed',
        valid_until: '2025-12-31',
        applied_to_loan_id: loans[6].id,
        description: '0.5% rate reduction for 12 consecutive on-time payments',
      },
      {
        user_id: userId,
        profile_id: profile.id,
        reward_type: 'limit_increase',
        reward_reason: 'consecutive_loans',
        reward_value: 2000000,
        status: 'active',
        valid_until: '2027-05-24',
        description: 'UGX 2M limit increase for completing 5 loans',
      },
      {
        user_id: userId,
        profile_id: profile.id,
        reward_type: 'fee_waiver',
        reward_reason: 'early_repayment',
        reward_value: 50000,
        status: 'active',
        valid_until: '2026-12-31',
        description: 'UGX 50,000 fee waiver for early repayment',
      },
      {
        user_id: userId,
        profile_id: profile.id,
        reward_type: 'cashback',
        reward_reason: 'referral',
        reward_value: 25000,
        status: 'active',
        valid_until: '2026-12-31',
        description: 'UGX 25,000 cashback per successful referral',
      },
      {
        user_id: userId,
        profile_id: profile.id,
        reward_type: 'priority_approval',
        reward_reason: 'savings_consistency',
        reward_value: 0,
        status: 'active',
        valid_until: '2027-05-24',
        description: 'Priority loan approval for consistent savings',
      },
    ]);

    // 12. Create Financial Health Report
    const healthReport = await base44.entities.FinancialHealthReport.create({
      user_id: userId,
      overall_score: 87,
      grade: 'A',
      generated_at: '2026-05-24T08:00:00Z',
      credit_pillar_score: 92,
      savings_pillar_score: 88,
      spending_pillar_score: 82,
      debt_pillar_score: 85,
      rule_flags: ['excellent_payment_history', 'healthy_savings_rate', 'diversified_portfolio'],
      ai_summary: 'Excellent financial health with strong credit history, consistent savings, and diversified investments. Continue maintaining on-time payments and consider increasing emergency fund.',
      ai_tips: [
        'Consider increasing emergency fund to 12 months expenses',
        'Diversify P2P investments across more risk bands',
        'Maximize loyalty points redemption for fee savings',
      ],
      recommendations: ['Increase savings rate by 5%', 'Review insurance coverage annually', 'Consider real estate investment'],
    });

    // 13. Create Revenue Transactions (platform revenue from this user)
    const revenue = await base44.entities.RevenueTransaction.bulkCreate([
      {
        transaction_type: 'loan_disbursement_fee',
        product_type: 'loan',
        amount: 60000,
        partner_id: userId,
        reference_id: loans[0].id,
        transaction_date: '2024-06-15T10:00:00Z',
        description: 'Disbursement fee - Loan 1',
      },
      {
        transaction_type: 'loan_disbursement_fee',
        product_type: 'loan',
        amount: 300000,
        partner_id: userId,
        reference_id: loans[7].id,
        transaction_date: '2026-02-01T10:00:00Z',
        description: 'Disbursement fee - Real Estate Loan',
      },
      {
        transaction_type: 'insurance_premium',
        product_type: 'insurance',
        amount: 450000,
        partner_id: userId,
        reference_id: policies[0].id,
        transaction_date: '2026-03-01T10:00:00Z',
        description: 'Vehicle insurance premium Q1 2026',
      },
      {
        transaction_type: 'p2p_investment_fee',
        product_type: 'p2p_loan',
        amount: 25000,
        partner_id: userId,
        reference_id: investments[0].id,
        transaction_date: '2025-03-15T10:00:00Z',
        description: 'P2P investment management fee',
      },
      {
        transaction_type: 'transaction_fee',
        product_type: 'loan',
        amount: 5000,
        partner_id: userId,
        reference_id: repayments[0].id,
        transaction_date: '2024-07-13T10:00:00Z',
        description: 'Mobile money transaction fee',
      },
    ]);

    // 14. Create Referral Events (simplified - schema has points_awarded field)
    const referrals = await base44.entities.ReferralEvent.bulkCreate([
      { referrer_id: userId, invitee_id: 'user_ref_001', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2024-09-01T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_002', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2024-11-15T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_003', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2025-02-01T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_004', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2025-04-20T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_005', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2025-07-10T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_006', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2025-10-05T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_007', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2025-12-15T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_008', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2026-02-10T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_009', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2026-04-05T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_010', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2026-05-15T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_011', referral_code_used: profile.referral_code, status: 'awarded', points_awarded: 500, awarded_date: '2026-05-20T10:00:00Z' },
      { referrer_id: userId, invitee_id: 'user_ref_012', referral_code_used: profile.referral_code, status: 'pending', points_awarded: 0 },
      { referrer_id: userId, invitee_id: 'user_ref_013', referral_code_used: profile.referral_code, status: 'pending', points_awarded: 0 },
      { referrer_id: userId, invitee_id: 'user_ref_014', referral_code_used: profile.referral_code, status: 'pending', points_awarded: 0 },
    ]);

    // 15. Create User Assets and Liabilities (Net Worth)
    const assets = await base44.entities.UserAsset.bulkCreate([
      { user_id: userId, name: 'Residential Plot - Nakasero', type: 'real_estate', current_value: 45000000, original_value: 35000000, purchase_date: '2024-03-15', description: '50x100 plot in Nakasero' },
      { user_id: userId, name: 'TVS Raider 125cc', type: 'vehicle', current_value: 22000000, original_value: 25000000, purchase_date: '2025-01-10', description: 'Motorcycle for business' },
      { user_id: userId, name: 'Total Savings Pockets', type: 'external_cash', current_value: 87800000, original_value: 87800000, purchase_date: '2026-05-24', description: 'All savings pockets combined' },
      { user_id: userId, name: 'P2P Investment Portfolio', type: 'other', current_value: 15000000, original_value: 15000000, purchase_date: '2026-05-24', description: 'Total P2P investments' },
      { user_id: userId, name: 'Kampala Tech Services', type: 'business_equipment', current_value: 60000000, original_value: 40000000, purchase_date: '2023-06-01', description: 'Electronics retail and repair business' },
    ]);

    const liabilities = await base44.entities.UserLiability.bulkCreate([
      { user_id: userId, name: 'Business Expansion Loan', type: 'business_loan', outstanding_balance: 3200000, original_amount: 8000000, start_date: '2025-12-01', description: 'Loan for business expansion' },
      { user_id: userId, name: 'Real Estate Loan', type: 'personal_loan', outstanding_balance: 8100000, original_amount: 10000000, start_date: '2026-02-01', description: 'Land purchase loan' },
      { user_id: userId, name: 'Working Capital Loan', type: 'business_loan', outstanding_balance: 5000000, original_amount: 5000000, start_date: '2026-05-20', description: 'Working capital loan' },
      { user_id: userId, name: 'Outstanding Insurance Premiums', type: 'other', outstanding_balance: 1350000, original_amount: 1350000, start_date: '2026-05-24', description: 'Annual premiums due in next 12 months' },
    ]);

    // Summary
    const totalSavings = pockets.reduce((sum, p) => sum + p.current_balance, 0);
    const totalInvested = investments.reduce((sum, i) => sum + i.amount_invested, 0);
    const totalInsurancePaid = policies.reduce((sum, p) => sum + p.total_premiums_paid, 0);
    const totalLoansReceived = loans.reduce((sum, l) => sum + l.amount_approved, 0);
    const totalActiveLoans = loans.filter(l => ['active', 'disbursed'].includes(l.status)).reduce((sum, l) => sum + l.outstanding_balance, 0);

    return Response.json({
      success: true,
      summary: {
        profile_created: true,
        credit_scores_created: creditScores.length,
        loans_created: loans.length,
        repayments_created: repayments.length,
        savings_pockets_created: pockets.length,
        insurance_policies_created: policies.length,
        investments_created: investments.length,
        expenses_created: expenses.length,
        notifications_created: notifications.length,
        badges_created: badges.length,
        rewards_created: rewards.length,
        health_report_created: true,
        revenue_transactions_created: revenue.length,
        referrals_created: referrals.length,
        assets_created: assets.length,
        liabilities_created: liabilities.length,
        total_savings: totalSavings,
        total_invested: totalInvested,
        total_insurance_paid: totalInsurancePaid,
        total_loans_received: totalLoansReceived,
        total_active_debt: totalActiveLoans,
        net_worth_estimate: assets.reduce((s, a) => s + a.current_value, 0) - liabilities.reduce((s, l) => s + l.outstanding_balance, 0),
      },
    });
  } catch (error) {
    return Response.json({ error: error.message, stack: error.stack }, { status: 500 });
  }
});